dist: trusty
sudo: false
language: rust

cache:
  - cargo: true

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  include:
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - export CARGO_INCREMENTAL=0
script:
  - cargo update
  - cargo test --all
