[package]
name = "example-custom-logging"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "custom-logging"
path = "src/main.rs"
doc = false

[dependencies]
finchers = "0.12"
slog = "2.4"
sloggers = "0.2"
